export const designationsJSON = [
  'Laravel Developer',
  'Sr. PHP Developer',
  'Wordpress Backend Developer',
  'Wordpress Frontend Developer',
  'Technical Product Manager',
  'QA',
  'Product Head',
  'Dev Head',
  'Design Head',
  'Project Coordinator',
  'Account Manager',
  'HR',
  'H/W Engineer',
  'Content Writer',
  'React Native',
  'UI/UX',
  'Digital Marketing Executive',
  'Operations Head',
  'SEO',
  'VP Marketing',
  'VA',
  'Director / Business Co-ordinator',
  'Director / Business Manager',
  'COO',
  'Founder / CEO',
  'Data Entry Operator',
  'Customer Success Manager',
  'Project Manager',
  'Python Developer (Ai/ML)',
  'Custom QA',
  'Finance & Account Manager',
  'Custom Designer',
  'Demo',
  'Product Manager (AI)',
  'Node JS Developer',
  'Office Assistant',
  'PPC Executive',
  'Growth Marketer',
];
